import pandas as pd
from pathlib import Path

print("=" * 70)
print("OLYMPIAD INTELLIGENCE - MODEL REPORT")
print("=" * 70)

DATA_PATH = Path("data/processed/difficulty_predictions.csv")
OUTPUT_DIR = Path("data/processed")
REPORT_PATH = OUTPUT_DIR / "difficulty_model_report.txt"

df = pd.read_csv(DATA_PATH)

print(f"\nLoaded {len(df)} predictions.")

# Basic metrics
mean_error = df["actual_difficulty"].sub(
    df["predicted_difficulty"]
).mean()

mae = df["absolute_error"].mean()

max_error = df["absolute_error"].max()

rmse = (
    ((df["actual_difficulty"] - df["predicted_difficulty"]) ** 2).mean()
) ** 0.5

# Error groups
excellent = (df["absolute_error"] <= 2).sum()
good = ((df["absolute_error"] > 2) &
        (df["absolute_error"] <= 5)).sum()
moderate = ((df["absolute_error"] > 5) &
            (df["absolute_error"] <= 10)).sum()
large = (df["absolute_error"] > 10).sum()

# Largest errors
largest_errors = df.sort_values(
    "absolute_error",
    ascending=False
).head(10)

report = []

report.append("=" * 70)
report.append("OLYMPIAD INTELLIGENCE - DIFFICULTY MODEL REPORT")
report.append("=" * 70)

report.append("\nDATASET")
report.append("-" * 70)
report.append(f"Prediction samples: {len(df)}")
report.append(f"Features: {len(df.columns) - 3}")

report.append("\nMODEL PERFORMANCE")
report.append("-" * 70)
report.append(f"Mean Error: {mean_error:.4f}")
report.append(f"MAE:        {mae:.4f}")
report.append(f"RMSE:       {rmse:.4f}")
report.append(f"Max Error:  {max_error:.4f}")

report.append("\nERROR DISTRIBUTION")
report.append("-" * 70)
report.append(f"Absolute error <= 2:  {excellent}")
report.append(f"Absolute error 2-5:   {good}")
report.append(f"Absolute error 5-10:  {moderate}")
report.append(f"Absolute error > 10:  {large}")

report.append("\nLARGEST PREDICTION ERRORS")
report.append("-" * 70)
report.append(
    largest_errors[
        [
            "actual_difficulty",
            "predicted_difficulty",
            "absolute_error"
        ]
    ].to_string(index=False)
)

report.append("\nINTERPRETATION")
report.append("-" * 70)
report.append(
    "The model predictions are compared against the difficulty score "
    "generated by the current difficulty-engine methodology."
)

report.append(
    "This evaluation measures how well the machine-learning model "
    "reproduces the existing engineered difficulty score."
)

report.append(
    "It does not yet establish agreement with human olympiad "
    "experts or official competition difficulty ratings."
)

REPORT_TEXT = "\n".join(report)

print("\n" + REPORT_TEXT)

REPORT_PATH.write_text(
    REPORT_TEXT,
    encoding="utf-8"
)

print("\n" + "=" * 70)
print("Report saved:")
print(REPORT_PATH)
print("=" * 70)